---
# Site settings
locale:  "en"
title:  "jreel"
title_separator:  " | "
name:  "Jessica Reel"
tagline:  "yet another github user site"
description:  "my personal site / dev portfolio"
url:  ""
baseurl:  ""
logo: # path to your logo.png

disqus:  #false
comments:
  provider: # false (default), "disqus", "discourse", "google-plus", "custom"
  disqus:
    shortname: # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org


atom_feed:
  path:  # blank (default) uses feed.xml


# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:

# Social sharing
github:
  username:  "jreel"
  repo: https://github.com/jreel.github.io
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id:


# Site author & social media stuff
author:
  name:  "Jessica Reel"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "I am an amazing person."
  location: "Somewhere"
  url:  "https://github.com/jreel"
  email: jessica.reel@outlook.com
  codepen:
  flickr:
  facebook:
  github: jreel
  google_plus:
  instagram:
  linkedin:
  soundcloud:
  stackoverflow: # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  twitter:
  youtube: # "https://youtube.com/c/MichaelRoseDesign"

footer-links:
  email: jessica.reel@outlook.com
  facebook:
  github: jreel
  instagram:
  linkedin:
  rss: atom.xml
  twitter:
  stackoverflow:
  youtube:
  googleplus:


# Layout & build settings - defaults
defaults:
  -
    scope:
      path:  ""  # an empty string here means all files in the project
      type:  "posts"
    values:
      layout:  "post-default"
      author_profile: true
      read_time: true
      comments: #true
      share: true
      related: true
  -
    scope:
      path:  ""
      type:  "pages"
    values:
      layout:  "page-default"


# collections:


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
excerpt_separator: <!--more-->

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - CNAME
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore /docs
  - /test # ignore /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering content
show_drafts:  null
limit_posts:  0
future:  false
unpublished:  false

# Conversion
markdown:  kramdown
highlighter:  rouge
lsi:  true  # produces an index for related posts, requires classifier-reborn plugin
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: expanded # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
